<title>
  <%= Page.Title %>
</title>
<link runat="server" rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
<link runat="server" rel="icon" type="image/ico" href="~/favicon.ico" />
<script src="http://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<link href="/css/StyleSheet.css" rel="stylesheet" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<script src="/js/JavaScript.js"></script>